services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: reservera
      POSTGRES_USER: reservera
      POSTGRES_PASSWORD: reservera123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@reservera.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
